// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.6.1
// source: tpuService.proto

package tpuService

import (
	empty "github.com/golang/protobuf/ptypes/empty"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetTpuByCountry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Country string `protobuf:"bytes,1,opt,name=country,proto3" json:"country,omitempty"`
}

func (x *GetTpuByCountry) Reset() {
	*x = GetTpuByCountry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tpuService_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTpuByCountry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTpuByCountry) ProtoMessage() {}

func (x *GetTpuByCountry) ProtoReflect() protoreflect.Message {
	mi := &file_tpuService_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTpuByCountry.ProtoReflect.Descriptor instead.
func (*GetTpuByCountry) Descriptor() ([]byte, []int) {
	return file_tpuService_proto_rawDescGZIP(), []int{0}
}

func (x *GetTpuByCountry) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

type GetTopTpu struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Top uint64 `protobuf:"varint,1,opt,name=top,proto3" json:"top,omitempty"`
}

func (x *GetTopTpu) Reset() {
	*x = GetTopTpu{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tpuService_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTopTpu) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTopTpu) ProtoMessage() {}

func (x *GetTopTpu) ProtoReflect() protoreflect.Message {
	mi := &file_tpuService_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTopTpu.ProtoReflect.Descriptor instead.
func (*GetTopTpu) Descriptor() ([]byte, []int) {
	return file_tpuService_proto_rawDescGZIP(), []int{1}
}

func (x *GetTopTpu) GetTop() uint64 {
	if x != nil {
		return x.Top
	}
	return 0
}

type Validator struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tpu string `protobuf:"bytes,1,opt,name=tpu,proto3" json:"tpu,omitempty"`
}

func (x *Validator) Reset() {
	*x = Validator{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tpuService_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Validator) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Validator) ProtoMessage() {}

func (x *Validator) ProtoReflect() protoreflect.Message {
	mi := &file_tpuService_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Validator.ProtoReflect.Descriptor instead.
func (*Validator) Descriptor() ([]byte, []int) {
	return file_tpuService_proto_rawDescGZIP(), []int{2}
}

func (x *Validator) GetTpu() string {
	if x != nil {
		return x.Tpu
	}
	return ""
}

type Validators struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Validators []*Validator `protobuf:"bytes,1,rep,name=validators,proto3" json:"validators,omitempty"`
}

func (x *Validators) Reset() {
	*x = Validators{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tpuService_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Validators) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Validators) ProtoMessage() {}

func (x *Validators) ProtoReflect() protoreflect.Message {
	mi := &file_tpuService_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Validators.ProtoReflect.Descriptor instead.
func (*Validators) Descriptor() ([]byte, []int) {
	return file_tpuService_proto_rawDescGZIP(), []int{3}
}

func (x *Validators) GetValidators() []*Validator {
	if x != nil {
		return x.Validators
	}
	return nil
}

type ValidatorsMapField struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   uint64     `protobuf:"varint,1,opt,name=key,proto3" json:"key,omitempty"`
	Value *Validator `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *ValidatorsMapField) Reset() {
	*x = ValidatorsMapField{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tpuService_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ValidatorsMapField) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidatorsMapField) ProtoMessage() {}

func (x *ValidatorsMapField) ProtoReflect() protoreflect.Message {
	mi := &file_tpuService_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidatorsMapField.ProtoReflect.Descriptor instead.
func (*ValidatorsMapField) Descriptor() ([]byte, []int) {
	return file_tpuService_proto_rawDescGZIP(), []int{4}
}

func (x *ValidatorsMapField) GetKey() uint64 {
	if x != nil {
		return x.Key
	}
	return 0
}

func (x *ValidatorsMapField) GetValue() *Validator {
	if x != nil {
		return x.Value
	}
	return nil
}

type ValidatorsMap struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MapField []*Validator `protobuf:"bytes,1,rep,name=map_field,json=mapField,proto3" json:"map_field,omitempty"`
}

func (x *ValidatorsMap) Reset() {
	*x = ValidatorsMap{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tpuService_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ValidatorsMap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidatorsMap) ProtoMessage() {}

func (x *ValidatorsMap) ProtoReflect() protoreflect.Message {
	mi := &file_tpuService_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidatorsMap.ProtoReflect.Descriptor instead.
func (*ValidatorsMap) Descriptor() ([]byte, []int) {
	return file_tpuService_proto_rawDescGZIP(), []int{5}
}

func (x *ValidatorsMap) GetMapField() []*Validator {
	if x != nil {
		return x.MapField
	}
	return nil
}

var File_tpuService_proto protoreflect.FileDescriptor

var file_tpuService_proto_rawDesc = []byte{
	0x0a, 0x10, 0x74, 0x70, 0x75, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x0a, 0x74, 0x70, 0x75, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x1a, 0x1b,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f,
	0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x2b, 0x0a, 0x0f, 0x47,
	0x65, 0x74, 0x54, 0x70, 0x75, 0x42, 0x79, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x18,
	0x0a, 0x07, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x22, 0x1d, 0x0a, 0x09, 0x47, 0x65, 0x74, 0x54,
	0x6f, 0x70, 0x54, 0x70, 0x75, 0x12, 0x10, 0x0a, 0x03, 0x74, 0x6f, 0x70, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x03, 0x74, 0x6f, 0x70, 0x22, 0x1d, 0x0a, 0x09, 0x56, 0x61, 0x6c, 0x69, 0x64,
	0x61, 0x74, 0x6f, 0x72, 0x12, 0x10, 0x0a, 0x03, 0x74, 0x70, 0x75, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x74, 0x70, 0x75, 0x22, 0x43, 0x0a, 0x0a, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61,
	0x74, 0x6f, 0x72, 0x73, 0x12, 0x35, 0x0a, 0x0a, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x6f,
	0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x74, 0x70, 0x75, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x6f, 0x72, 0x52,
	0x0a, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x6f, 0x72, 0x73, 0x22, 0x53, 0x0a, 0x12, 0x56,
	0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x6f, 0x72, 0x73, 0x4d, 0x61, 0x70, 0x46, 0x69, 0x65, 0x6c,
	0x64, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03,
	0x6b, 0x65, 0x79, 0x12, 0x2b, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x15, 0x2e, 0x74, 0x70, 0x75, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e,
	0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x6f, 0x72, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x22, 0x43, 0x0a, 0x0d, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x6f, 0x72, 0x73, 0x4d, 0x61,
	0x70, 0x12, 0x32, 0x0a, 0x09, 0x6d, 0x61, 0x70, 0x5f, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x74, 0x70, 0x75, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2e, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x6f, 0x72, 0x52, 0x08, 0x6d, 0x61, 0x70,
	0x46, 0x69, 0x65, 0x6c, 0x64, 0x32, 0xdd, 0x01, 0x0a, 0x0a, 0x54, 0x70, 0x75, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x12, 0x48, 0x0a, 0x0f, 0x67, 0x65, 0x74, 0x54, 0x70, 0x75, 0x42, 0x79,
	0x43, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x1b, 0x2e, 0x74, 0x70, 0x75, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x54, 0x70, 0x75, 0x42, 0x79, 0x43, 0x6f, 0x75,
	0x6e, 0x74, 0x72, 0x79, 0x1a, 0x16, 0x2e, 0x74, 0x70, 0x75, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2e, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x6f, 0x72, 0x73, 0x22, 0x00, 0x12, 0x3c,
	0x0a, 0x09, 0x67, 0x65, 0x74, 0x54, 0x6f, 0x70, 0x54, 0x70, 0x75, 0x12, 0x15, 0x2e, 0x74, 0x70,
	0x75, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x54, 0x6f, 0x70, 0x54,
	0x70, 0x75, 0x1a, 0x16, 0x2e, 0x74, 0x70, 0x75, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e,
	0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x6f, 0x72, 0x73, 0x22, 0x00, 0x12, 0x47, 0x0a, 0x10,
	0x67, 0x65, 0x74, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x6f, 0x72, 0x73, 0x4d, 0x61, 0x70,
	0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x19, 0x2e, 0x74, 0x70, 0x75, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x6f, 0x72, 0x73,
	0x4d, 0x61, 0x70, 0x22, 0x00, 0x42, 0x17, 0x5a, 0x15, 0x74, 0x70, 0x75, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2f, 0x74, 0x70, 0x75, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_tpuService_proto_rawDescOnce sync.Once
	file_tpuService_proto_rawDescData = file_tpuService_proto_rawDesc
)

func file_tpuService_proto_rawDescGZIP() []byte {
	file_tpuService_proto_rawDescOnce.Do(func() {
		file_tpuService_proto_rawDescData = protoimpl.X.CompressGZIP(file_tpuService_proto_rawDescData)
	})
	return file_tpuService_proto_rawDescData
}

var file_tpuService_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_tpuService_proto_goTypes = []interface{}{
	(*GetTpuByCountry)(nil),    // 0: tpuService.GetTpuByCountry
	(*GetTopTpu)(nil),          // 1: tpuService.GetTopTpu
	(*Validator)(nil),          // 2: tpuService.Validator
	(*Validators)(nil),         // 3: tpuService.Validators
	(*ValidatorsMapField)(nil), // 4: tpuService.ValidatorsMapField
	(*ValidatorsMap)(nil),      // 5: tpuService.ValidatorsMap
	(*empty.Empty)(nil),        // 6: google.protobuf.Empty
}
var file_tpuService_proto_depIdxs = []int32{
	2, // 0: tpuService.Validators.validators:type_name -> tpuService.Validator
	2, // 1: tpuService.ValidatorsMapField.value:type_name -> tpuService.Validator
	2, // 2: tpuService.ValidatorsMap.map_field:type_name -> tpuService.Validator
	0, // 3: tpuService.TpuService.getTpuByCountry:input_type -> tpuService.GetTpuByCountry
	1, // 4: tpuService.TpuService.getTopTpu:input_type -> tpuService.GetTopTpu
	6, // 5: tpuService.TpuService.getValidatorsMap:input_type -> google.protobuf.Empty
	3, // 6: tpuService.TpuService.getTpuByCountry:output_type -> tpuService.Validators
	3, // 7: tpuService.TpuService.getTopTpu:output_type -> tpuService.Validators
	5, // 8: tpuService.TpuService.getValidatorsMap:output_type -> tpuService.ValidatorsMap
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_tpuService_proto_init() }
func file_tpuService_proto_init() {
	if File_tpuService_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_tpuService_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTpuByCountry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tpuService_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTopTpu); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tpuService_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Validator); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tpuService_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Validators); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tpuService_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ValidatorsMapField); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tpuService_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ValidatorsMap); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_tpuService_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tpuService_proto_goTypes,
		DependencyIndexes: file_tpuService_proto_depIdxs,
		MessageInfos:      file_tpuService_proto_msgTypes,
	}.Build()
	File_tpuService_proto = out.File
	file_tpuService_proto_rawDesc = nil
	file_tpuService_proto_goTypes = nil
	file_tpuService_proto_depIdxs = nil
}
