// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.21.1
// source: collectionExtractorService/collectionExtractorService.proto

package collectionExtractorService

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NftEntity struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mint     string   `protobuf:"bytes,1,opt,name=Mint,proto3" json:"Mint,omitempty"`
	Rarity   float32  `protobuf:"fixed32,2,opt,name=Rarity,proto3" json:"Rarity,omitempty"`
	Creators []string `protobuf:"bytes,3,rep,name=Creators,proto3" json:"Creators,omitempty"`
}

func (x *NftEntity) Reset() {
	*x = NftEntity{}
	if protoimpl.UnsafeEnabled {
		mi := &file_collectionExtractorService_collectionExtractorService_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NftEntity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NftEntity) ProtoMessage() {}

func (x *NftEntity) ProtoReflect() protoreflect.Message {
	mi := &file_collectionExtractorService_collectionExtractorService_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NftEntity.ProtoReflect.Descriptor instead.
func (*NftEntity) Descriptor() ([]byte, []int) {
	return file_collectionExtractorService_collectionExtractorService_proto_rawDescGZIP(), []int{0}
}

func (x *NftEntity) GetMint() string {
	if x != nil {
		return x.Mint
	}
	return ""
}

func (x *NftEntity) GetRarity() float32 {
	if x != nil {
		return x.Rarity
	}
	return 0
}

func (x *NftEntity) GetCreators() []string {
	if x != nil {
		return x.Creators
	}
	return nil
}

type MarketAction struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ActionType    string  `protobuf:"bytes,1,opt,name=ActionType,proto3" json:"ActionType,omitempty"`
	EscrowAccount *string `protobuf:"bytes,2,opt,name=EscrowAccount,proto3,oneof" json:"EscrowAccount,omitempty"`
	Price         *uint64 `protobuf:"varint,3,opt,name=Price,proto3,oneof" json:"Price,omitempty"`
	Mint          string  `protobuf:"bytes,4,opt,name=Mint,proto3" json:"Mint,omitempty"`
	Owner         string  `protobuf:"bytes,5,opt,name=Owner,proto3" json:"Owner,omitempty"`
	TimeStamp     string  `protobuf:"bytes,6,opt,name=TimeStamp,proto3" json:"TimeStamp,omitempty"`
}

func (x *MarketAction) Reset() {
	*x = MarketAction{}
	if protoimpl.UnsafeEnabled {
		mi := &file_collectionExtractorService_collectionExtractorService_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MarketAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarketAction) ProtoMessage() {}

func (x *MarketAction) ProtoReflect() protoreflect.Message {
	mi := &file_collectionExtractorService_collectionExtractorService_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarketAction.ProtoReflect.Descriptor instead.
func (*MarketAction) Descriptor() ([]byte, []int) {
	return file_collectionExtractorService_collectionExtractorService_proto_rawDescGZIP(), []int{1}
}

func (x *MarketAction) GetActionType() string {
	if x != nil {
		return x.ActionType
	}
	return ""
}

func (x *MarketAction) GetEscrowAccount() string {
	if x != nil && x.EscrowAccount != nil {
		return *x.EscrowAccount
	}
	return ""
}

func (x *MarketAction) GetPrice() uint64 {
	if x != nil && x.Price != nil {
		return *x.Price
	}
	return 0
}

func (x *MarketAction) GetMint() string {
	if x != nil {
		return x.Mint
	}
	return ""
}

func (x *MarketAction) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *MarketAction) GetTimeStamp() string {
	if x != nil {
		return x.TimeStamp
	}
	return ""
}

type GetCollectionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GetCollectionID string `protobuf:"bytes,1,opt,name=GetCollectionID,proto3" json:"GetCollectionID,omitempty"`
	CmType          string `protobuf:"bytes,2,opt,name=CmType,proto3" json:"CmType,omitempty"`
	RpcUrl          string `protobuf:"bytes,3,opt,name=RpcUrl,proto3" json:"RpcUrl,omitempty"`
	IsForce         bool   `protobuf:"varint,4,opt,name=isForce,proto3" json:"isForce,omitempty"`
}

func (x *GetCollectionRequest) Reset() {
	*x = GetCollectionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_collectionExtractorService_collectionExtractorService_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCollectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCollectionRequest) ProtoMessage() {}

func (x *GetCollectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_collectionExtractorService_collectionExtractorService_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCollectionRequest.ProtoReflect.Descriptor instead.
func (*GetCollectionRequest) Descriptor() ([]byte, []int) {
	return file_collectionExtractorService_collectionExtractorService_proto_rawDescGZIP(), []int{2}
}

func (x *GetCollectionRequest) GetGetCollectionID() string {
	if x != nil {
		return x.GetCollectionID
	}
	return ""
}

func (x *GetCollectionRequest) GetCmType() string {
	if x != nil {
		return x.CmType
	}
	return ""
}

func (x *GetCollectionRequest) GetRpcUrl() string {
	if x != nil {
		return x.RpcUrl
	}
	return ""
}

func (x *GetCollectionRequest) GetIsForce() bool {
	if x != nil {
		return x.IsForce
	}
	return false
}

type GetCollectionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NftEntities []*NftEntity `protobuf:"bytes,1,rep,name=nftEntities,proto3" json:"nftEntities,omitempty"`
}

func (x *GetCollectionResponse) Reset() {
	*x = GetCollectionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_collectionExtractorService_collectionExtractorService_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCollectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCollectionResponse) ProtoMessage() {}

func (x *GetCollectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_collectionExtractorService_collectionExtractorService_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCollectionResponse.ProtoReflect.Descriptor instead.
func (*GetCollectionResponse) Descriptor() ([]byte, []int) {
	return file_collectionExtractorService_collectionExtractorService_proto_rawDescGZIP(), []int{3}
}

func (x *GetCollectionResponse) GetNftEntities() []*NftEntity {
	if x != nil {
		return x.NftEntities
	}
	return nil
}

type GetMarketDataRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Nfts      []string `protobuf:"bytes,1,rep,name=nfts,proto3" json:"nfts,omitempty"`
	ChunkSize int64    `protobuf:"varint,2,opt,name=chunkSize,proto3" json:"chunkSize,omitempty"`
	RpcUrl    string   `protobuf:"bytes,3,opt,name=RpcUrl,proto3" json:"RpcUrl,omitempty"`
}

func (x *GetMarketDataRequest) Reset() {
	*x = GetMarketDataRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_collectionExtractorService_collectionExtractorService_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMarketDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMarketDataRequest) ProtoMessage() {}

func (x *GetMarketDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_collectionExtractorService_collectionExtractorService_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMarketDataRequest.ProtoReflect.Descriptor instead.
func (*GetMarketDataRequest) Descriptor() ([]byte, []int) {
	return file_collectionExtractorService_collectionExtractorService_proto_rawDescGZIP(), []int{4}
}

func (x *GetMarketDataRequest) GetNfts() []string {
	if x != nil {
		return x.Nfts
	}
	return nil
}

func (x *GetMarketDataRequest) GetChunkSize() int64 {
	if x != nil {
		return x.ChunkSize
	}
	return 0
}

func (x *GetMarketDataRequest) GetRpcUrl() string {
	if x != nil {
		return x.RpcUrl
	}
	return ""
}

type GetMarketDataResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MarketActions []*MarketAction `protobuf:"bytes,1,rep,name=marketActions,proto3" json:"marketActions,omitempty"`
}

func (x *GetMarketDataResponse) Reset() {
	*x = GetMarketDataResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_collectionExtractorService_collectionExtractorService_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMarketDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMarketDataResponse) ProtoMessage() {}

func (x *GetMarketDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_collectionExtractorService_collectionExtractorService_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMarketDataResponse.ProtoReflect.Descriptor instead.
func (*GetMarketDataResponse) Descriptor() ([]byte, []int) {
	return file_collectionExtractorService_collectionExtractorService_proto_rawDescGZIP(), []int{5}
}

func (x *GetMarketDataResponse) GetMarketActions() []*MarketAction {
	if x != nil {
		return x.MarketActions
	}
	return nil
}

var File_collectionExtractorService_collectionExtractorService_proto protoreflect.FileDescriptor

var file_collectionExtractorService_collectionExtractorService_proto_rawDesc = []byte{
	0x0a, 0x3b, 0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x45, 0x78, 0x74, 0x72,
	0x61, 0x63, 0x74, 0x6f, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x63, 0x6f, 0x6c,
	0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x45, 0x78, 0x74, 0x72, 0x61, 0x63, 0x74, 0x6f, 0x72,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x1a, 0x63,
	0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x45, 0x78, 0x74, 0x72, 0x61, 0x63, 0x74,
	0x6f, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x22, 0x53, 0x0a, 0x09, 0x4e, 0x66, 0x74,
	0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x4d, 0x69, 0x6e, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4d, 0x69, 0x6e, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x52, 0x61,
	0x72, 0x69, 0x74, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x06, 0x52, 0x61, 0x72, 0x69,
	0x74, 0x79, 0x12, 0x1a, 0x0a, 0x08, 0x43, 0x72, 0x65, 0x61, 0x74, 0x6f, 0x72, 0x73, 0x18, 0x03,
	0x20, 0x03, 0x28, 0x09, 0x52, 0x08, 0x43, 0x72, 0x65, 0x61, 0x74, 0x6f, 0x72, 0x73, 0x22, 0xd8,
	0x01, 0x0a, 0x0c, 0x4d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x1e, 0x0a, 0x0a, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0a, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x12,
	0x29, 0x0a, 0x0d, 0x45, 0x73, 0x63, 0x72, 0x6f, 0x77, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x0d, 0x45, 0x73, 0x63, 0x72, 0x6f, 0x77,
	0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x88, 0x01, 0x01, 0x12, 0x19, 0x0a, 0x05, 0x50, 0x72,
	0x69, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x48, 0x01, 0x52, 0x05, 0x50, 0x72, 0x69,
	0x63, 0x65, 0x88, 0x01, 0x01, 0x12, 0x12, 0x0a, 0x04, 0x4d, 0x69, 0x6e, 0x74, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x4d, 0x69, 0x6e, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x4f, 0x77, 0x6e,
	0x65, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x4f, 0x77, 0x6e, 0x65, 0x72, 0x12,
	0x1c, 0x0a, 0x09, 0x54, 0x69, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x54, 0x69, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x6d, 0x70, 0x42, 0x10, 0x0a,
	0x0e, 0x5f, 0x45, 0x73, 0x63, 0x72, 0x6f, 0x77, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x42,
	0x08, 0x0a, 0x06, 0x5f, 0x50, 0x72, 0x69, 0x63, 0x65, 0x22, 0x8a, 0x01, 0x0a, 0x14, 0x47, 0x65,
	0x74, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x28, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x47, 0x65, 0x74,
	0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x12, 0x16, 0x0a, 0x06,
	0x43, 0x6d, 0x54, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x43, 0x6d,
	0x54, 0x79, 0x70, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x52, 0x70, 0x63, 0x55, 0x72, 0x6c, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x52, 0x70, 0x63, 0x55, 0x72, 0x6c, 0x12, 0x18, 0x0a, 0x07,
	0x69, 0x73, 0x46, 0x6f, 0x72, 0x63, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x69,
	0x73, 0x46, 0x6f, 0x72, 0x63, 0x65, 0x22, 0x60, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x6c,
	0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x47, 0x0a, 0x0b, 0x6e, 0x66, 0x74, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x69, 0x65, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x25, 0x2e, 0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x45, 0x78, 0x74, 0x72, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2e, 0x4e, 0x66, 0x74, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x52, 0x0b, 0x6e, 0x66, 0x74,
	0x45, 0x6e, 0x74, 0x69, 0x74, 0x69, 0x65, 0x73, 0x22, 0x60, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x4d,
	0x61, 0x72, 0x6b, 0x65, 0x74, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x66, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x66, 0x74, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x53, 0x69, 0x7a,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x53, 0x69,
	0x7a, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x52, 0x70, 0x63, 0x55, 0x72, 0x6c, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x52, 0x70, 0x63, 0x55, 0x72, 0x6c, 0x22, 0x67, 0x0a, 0x15, 0x47, 0x65,
	0x74, 0x4d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x4e, 0x0a, 0x0d, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x41, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x28, 0x2e, 0x63, 0x6f, 0x6c,
	0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x45, 0x78, 0x74, 0x72, 0x61, 0x63, 0x74, 0x6f, 0x72,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x4d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x41, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0d, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x41, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x32, 0x8c, 0x02, 0x0a, 0x1a, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x45, 0x78, 0x74, 0x72, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x12, 0x76, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x30, 0x2e, 0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x45, 0x78, 0x74, 0x72, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2e, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x31, 0x2e, 0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x45, 0x78, 0x74, 0x72, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x76, 0x0a, 0x0d, 0x47, 0x65,
	0x74, 0x4d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x44, 0x61, 0x74, 0x61, 0x12, 0x30, 0x2e, 0x63, 0x6f,
	0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x45, 0x78, 0x74, 0x72, 0x61, 0x63, 0x74, 0x6f,
	0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x4d, 0x61, 0x72, 0x6b,
	0x65, 0x74, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x31, 0x2e,
	0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x45, 0x78, 0x74, 0x72, 0x61, 0x63,
	0x74, 0x6f, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x4d, 0x61,
	0x72, 0x6b, 0x65, 0x74, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x42, 0x27, 0x5a, 0x25, 0x74, 0x70, 0x75, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2f, 0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x45, 0x78, 0x74, 0x72, 0x61,
	0x63, 0x74, 0x6f, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_collectionExtractorService_collectionExtractorService_proto_rawDescOnce sync.Once
	file_collectionExtractorService_collectionExtractorService_proto_rawDescData = file_collectionExtractorService_collectionExtractorService_proto_rawDesc
)

func file_collectionExtractorService_collectionExtractorService_proto_rawDescGZIP() []byte {
	file_collectionExtractorService_collectionExtractorService_proto_rawDescOnce.Do(func() {
		file_collectionExtractorService_collectionExtractorService_proto_rawDescData = protoimpl.X.CompressGZIP(file_collectionExtractorService_collectionExtractorService_proto_rawDescData)
	})
	return file_collectionExtractorService_collectionExtractorService_proto_rawDescData
}

var file_collectionExtractorService_collectionExtractorService_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_collectionExtractorService_collectionExtractorService_proto_goTypes = []interface{}{
	(*NftEntity)(nil),             // 0: collectionExtractorService.NftEntity
	(*MarketAction)(nil),          // 1: collectionExtractorService.MarketAction
	(*GetCollectionRequest)(nil),  // 2: collectionExtractorService.GetCollectionRequest
	(*GetCollectionResponse)(nil), // 3: collectionExtractorService.GetCollectionResponse
	(*GetMarketDataRequest)(nil),  // 4: collectionExtractorService.GetMarketDataRequest
	(*GetMarketDataResponse)(nil), // 5: collectionExtractorService.GetMarketDataResponse
}
var file_collectionExtractorService_collectionExtractorService_proto_depIdxs = []int32{
	0, // 0: collectionExtractorService.GetCollectionResponse.nftEntities:type_name -> collectionExtractorService.NftEntity
	1, // 1: collectionExtractorService.GetMarketDataResponse.marketActions:type_name -> collectionExtractorService.MarketAction
	2, // 2: collectionExtractorService.CollectionExtractorService.GetCollection:input_type -> collectionExtractorService.GetCollectionRequest
	4, // 3: collectionExtractorService.CollectionExtractorService.GetMarketData:input_type -> collectionExtractorService.GetMarketDataRequest
	3, // 4: collectionExtractorService.CollectionExtractorService.GetCollection:output_type -> collectionExtractorService.GetCollectionResponse
	5, // 5: collectionExtractorService.CollectionExtractorService.GetMarketData:output_type -> collectionExtractorService.GetMarketDataResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_collectionExtractorService_collectionExtractorService_proto_init() }
func file_collectionExtractorService_collectionExtractorService_proto_init() {
	if File_collectionExtractorService_collectionExtractorService_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_collectionExtractorService_collectionExtractorService_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NftEntity); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_collectionExtractorService_collectionExtractorService_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MarketAction); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_collectionExtractorService_collectionExtractorService_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCollectionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_collectionExtractorService_collectionExtractorService_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCollectionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_collectionExtractorService_collectionExtractorService_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMarketDataRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_collectionExtractorService_collectionExtractorService_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMarketDataResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_collectionExtractorService_collectionExtractorService_proto_msgTypes[1].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_collectionExtractorService_collectionExtractorService_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_collectionExtractorService_collectionExtractorService_proto_goTypes,
		DependencyIndexes: file_collectionExtractorService_collectionExtractorService_proto_depIdxs,
		MessageInfos:      file_collectionExtractorService_collectionExtractorService_proto_msgTypes,
	}.Build()
	File_collectionExtractorService_collectionExtractorService_proto = out.File
	file_collectionExtractorService_collectionExtractorService_proto_rawDesc = nil
	file_collectionExtractorService_collectionExtractorService_proto_goTypes = nil
	file_collectionExtractorService_collectionExtractorService_proto_depIdxs = nil
}
